### ISSUE TITLE
Duplicate detection should produce org-mode output and display a temp buffer

### ISSUE THREAD

**Issue by swflint** [pprevos/denote-explore#17]
The command `denote-explore-identify-duplicate-notes` is difficult to use.  It simply outputs a list of duplicate notes, which must be extracted from the messages buffer.

**Comment by pprevos** [comment]
Hi Samuel,

Thanks for the UI improvement. The old function indeed was a bit lacking.

I updated the code to include attachments (files with non-denote extensions). Denote is more than a note-taking application and I use to it archive various types of files.

In my workflow, duplicates occur mostly when I manually rename files (PDF, photographs etc), which is why I wrote this function. Denote has built-in duplicate prevention so duplicate notes are impossible when generated with Denote itself.

Also fixed an bug with the file links. 

P:)
